# Site settings
title:       ANDY SHIMMIN
description: "Interaction Designer"
baseurl:     ""
url:         "https://ashimmin.github.io"

# Author
author:
  name:      "Andy Shimmin"
  url:       https://ashimmin.github.io
  email:     andersonrshimmin@gmail.com
  post_id:   {{post.tile}}


# Build settings
markdown:    kramdown

# Assets
sass:
  sass_dir:  _sass
  style:     compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate


# Permalinks
permalink:   /:title #change to :pretty if wanting date
paginate:    9


collections:
      links:
        output: true
        permalink: /:path/ #change to ""/links/:path/" if running into tagging problems
      posts:

assets:
    sources:
